# Imagen base con Python 3.11
FROM python:3.11-slim

# Crear directorio de la app dentro del contenedor
WORKDIR /app

# Copiar y instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el código de la app
COPY . .

# Exponer el puerto en el que correrá Uvicorn
EXPOSE 10000

# Comando para iniciar la app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10000"]
